<table class="table table-bordered table-striped">
    <th colspan="3">
        <?php echo $message; ?>
    </th>
    <tr>
        <td>#</td>
        <td width="400">File:line</td>
        <td>Function</td>
    </tr>
    <?php for($i = 0; $i < count($errorStackTrace); $i++) {?>
        <tr>
            <td>#<?php echo $i;?></td>
            <td>
                <?php echo $errorStackTrace[$i]['file'];?>:
                <?php echo $errorStackTrace[$i]['line'];?>
            </td>
            <td>
                <?php echo $errorStackTrace[$i]['function'];?><?php echo $errorStackTrace[$i]['params']; ?>
            </td>
        </tr>
    <?php } ?>
</table>