<?php

use GTErrorTracker\H\EventType;
?>

<div class="row">
    <span data-page-info="<?php echo $pageNum;?>"></span>
    <b><?php $this->GTTxt("Event Id"); ?>:</b><?php $this->item->show("event_logger_id");?><br>
    <b><?php $this->GTTxt("Date"); ?>:</b><?php $this->item->show("DateTimeFormat")?><br>
    <b><?php $this->GTTxt("Event Type"); ?>:</b><?php echo(EventType::getName($this->item->event_type));?><br>
    <b><?php $this->GTTxt("File:Line"); ?></b><br>
    <?php $this->item->show("event_file");?>:<?php $this->item->show("line");?><br>
    <b><?php $this->GTTxt("Event Message"); ?>:</b><br>
    <?php $this->item->show("message");?><br>
    <b><?php $this->GTTxt("User");?>:</b>

    <?php $user = $this->item->get_user();?>
    <?php if($user instanceof \GTErrorTracker\Model\GTUserInterface){?>
        <span class="user_info" data-user-id="<?php echo $user->getId(); ?>">
            <?php $user->show("DisplayName");?>
        </span>
    <?php } else {
        $this->GTTxt("No User available");
    }?><br>

    <b><?php $this->GTTxt("Device Id");?>:</b><?php $this->item->show("device_id");?>

</div>

<div class="row">
    <?php $this->GTTxt("Stack Trace"); ?>:<br>
    <?php $this->item->show("stack_trace");?>
</div>

<div class="row">

    <a href="#xdebug_message" class="toggle btn btn-muted">Show the xdebug message</a><br>
    <div id="xdebug_message" class="hidden">
        <?php echo $this->xdebug_message;?><br>
    </div>

    <a href="#variables_dump" class="toggle btn btn-muted">Show the variables dump</a><br>
    <div id="variables_dump" class="hidden">
        <?php echo $this->variables_dump;?><br>
    </div>

    <a href="#trace_dump" class="toggle btn btn-muted">Show the trace dump</a><br>
    <div id="trace_dump" class="hidden">
        <?php echo $this->trace_dump;?><br>
    </div>

</div>








