<div class="accordion-group">
    <div class="accordion-heading">
        <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            Xdebug Message
        </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
        <div class="accordion-inner">
            <table>
                <?php $this->item->show("xdebug_message"); ?>
            </table>
        </div>
    </div>
</div>